// Generated by gencpp from file realman_msgs/MoveJ.msg
// DO NOT EDIT!


#ifndef REALMAN_MSGS_MESSAGE_MOVEJ_H
#define REALMAN_MSGS_MESSAGE_MOVEJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realman_msgs
{
template <class ContainerAllocator>
struct MoveJ_
{
  typedef MoveJ_<ContainerAllocator> Type;

  MoveJ_()
    : joint()
    , speed(0.0)  {
      joint.assign(0.0);
  }
  MoveJ_(const ContainerAllocator& _alloc)
    : joint()
    , speed(0.0)  {
  (void)_alloc;
      joint.assign(0.0);
  }



   typedef boost::array<float, 6>  _joint_type;
  _joint_type joint;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::realman_msgs::MoveJ_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realman_msgs::MoveJ_<ContainerAllocator> const> ConstPtr;

}; // struct MoveJ_

typedef ::realman_msgs::MoveJ_<std::allocator<void> > MoveJ;

typedef boost::shared_ptr< ::realman_msgs::MoveJ > MoveJPtr;
typedef boost::shared_ptr< ::realman_msgs::MoveJ const> MoveJConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realman_msgs::MoveJ_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realman_msgs::MoveJ_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realman_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'realman_msgs': ['/home/nvidia/catkin_ws/src/RM_Robot/realman_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realman_msgs::MoveJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realman_msgs::MoveJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realman_msgs::MoveJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realman_msgs::MoveJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realman_msgs::MoveJ_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realman_msgs::MoveJ_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realman_msgs::MoveJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09c56834f3b1f08e2e81713c24160d02";
  }

  static const char* value(const ::realman_msgs::MoveJ_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09c56834f3b1f08eULL;
  static const uint64_t static_value2 = 0x2e81713c24160d02ULL;
};

template<class ContainerAllocator>
struct DataType< ::realman_msgs::MoveJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realman_msgs/MoveJ";
  }

  static const char* value(const ::realman_msgs::MoveJ_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realman_msgs::MoveJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] joint\n\
float32 speed\n\
";
  }

  static const char* value(const ::realman_msgs::MoveJ_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realman_msgs::MoveJ_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveJ_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realman_msgs::MoveJ_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realman_msgs::MoveJ_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint[i]);
    }
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALMAN_MSGS_MESSAGE_MOVEJ_H
